<script setup lang="ts">
const tenant = useActiveTenant(); const api = useStorefrontApi()
const loading = ref(true); const error = ref(''); const account = ref<any>(); const orders = ref<any[]>([]); const reservations = ref<any[]>([])
async function load() { if (!api.authenticated.value) return navigateTo('/login?redirect=/account'); loading.value = true; error.value = ''; try { const [a, o, r] = await Promise.all([api.request<any>('/account'), api.request<any>('/orders?limit=25'), api.request<any>('/reservations?limit=25')]); account.value = a.data; orders.value = o.data; reservations.value = r.data } catch (reason: any) { error.value = reason?.data?.message || reason?.message } finally { loading.value = false } }
onMounted(load)
async function logout() { try { await api.request('/token', { method: 'DELETE' }) } finally { api.saveSession(); await navigateTo('/login') } }
useSeoMeta({ title: () => `My account — ${tenant.value?.brand?.identity?.name || 'Account'}`, robots: 'noindex,nofollow' })
</script>
<template><div class="page section"><div class="container"><AsyncState :loading="loading" :error="error" :empty="false" @retry="load"><div v-if="account"><div class="section-headline"><div><span class="section-kicker">Customer account</span><h1>Hello, {{ account.first_name }}</h1></div><button class="btn" @click="logout">Sign out</button></div><div class="account-grid"><section class="card"><h2>Recent orders</h2><div v-if="orders.length" class="timeline-list"><article v-for="order in orders" :key="order.id"><div><strong>{{ order.number }}</strong><small>{{ order.location }} · {{ order.status.name }}</small></div><strong>{{ new Intl.NumberFormat(undefined, { style: 'currency', currency: tenant?.currency?.code || 'USD' }).format(order.total) }}</strong></article></div><p v-else>No orders yet. <NuxtLink to="/menu">Choose something delicious</NuxtLink>.</p></section><section class="card"><h2>Reservations</h2><div v-if="reservations.length" class="timeline-list"><article v-for="reservation in reservations" :key="reservation.id"><div><strong>{{ reservation.date }} at {{ reservation.time }}</strong><small>{{ reservation.location }} · {{ reservation.status.name }}</small></div><span>{{ reservation.guests }} guests</span></article></div><p v-else>No upcoming reservations. <NuxtLink to="/reservations">Book a table</NuxtLink>.</p></section></div></div></AsyncState></div></div></template>
