<script setup lang="ts">
import type { Location } from '~/types/storefront'
const tenant = useNuxtData<any>('tenant-bootstrap'); const api = useStorefrontApi(); const cart = useTenantCart()
const headers = import.meta.server ? useRequestHeaders(['host', 'x-forwarded-host', 'x-forwarded-proto']) : undefined
const { data: locations } = await useFetch<{ data: Location[] }>('/api/v1/storefront/locations', { headers })
const form = reactive({ location_id: 0, order_type: 'collection', first_name: '', last_name: '', telephone: '', comment: '', address_1: '', city: '', postcode: '' })
const busy = ref(false); const error = ref(''); const success = ref<number | null>(null)
async function submit() {
  if (!api.authenticated.value) return navigateTo('/login?redirect=/checkout')
  busy.value = true; error.value = ''
  const body: any = { location_id: form.location_id, order_type: form.order_type, first_name: form.first_name, last_name: form.last_name,
    telephone: form.telephone, comment: form.comment || undefined, items: cart.lines.value.map(line => ({ menu_id: line.id, quantity: line.quantity, options: line.selected_options || [] })) }
  if (form.order_type === 'delivery') body.address = { address_1: form.address_1, city: form.city, postcode: form.postcode, country_id: tenant.data.value.data.defaults.country_id }
  try { const result = await api.request<any>('/orders', { method: 'POST', headers: { 'Idempotency-Key': crypto.randomUUID() }, body }); success.value = result.data.id; cart.clear() }
  catch (reason: any) { error.value = reason?.data?.message || reason?.message || 'Your order could not be placed.' }
  finally { busy.value = false }
}
useSeoMeta({ title: () => `Checkout — ${tenant.data.value.data.brand.identity.name}`, robots: 'noindex,nofollow' })
</script>
<template><div class="page section"><div class="container"><div v-if="success" class="content-state success-state" role="status"><i class="ri-checkbox-circle-line"/><h1>Order received</h1><p>Your order number is #{{ success }}.</p><NuxtLink class="btn primary" to="/account">Track your order</NuxtLink></div><div v-else class="checkout-layout"><section><span class="section-kicker">Secure checkout</span><h1>Complete your order</h1><p v-if="error" class="notice error" role="alert">{{ error }}</p><form class="card form-grid" @submit.prevent="submit"><label class="full"><span>Location</span><select v-model.number="form.location_id" required><option :value="0" disabled>Select a location</option><option v-for="location in locations?.data" :key="location.id" :value="location.id">{{ location.name }}</option></select></label><fieldset class="full"><legend>Order type</legend><label class="radio"><input v-model="form.order_type" type="radio" value="collection"> Collection</label><label class="radio"><input v-model="form.order_type" type="radio" value="delivery"> Delivery</label></fieldset><label><span>First name</span><input v-model="form.first_name" required></label><label><span>Last name</span><input v-model="form.last_name" required></label><label class="full"><span>Telephone</span><input v-model="form.telephone" required></label><template v-if="form.order_type === 'delivery'"><label class="full"><span>Street address</span><input v-model="form.address_1" required></label><label><span>City</span><input v-model="form.city" required></label><label><span>Postcode</span><input v-model="form.postcode" required></label></template><label class="full"><span>Order notes</span><textarea v-model="form.comment" rows="3" maxlength="500"/></label><button class="btn primary full" :disabled="busy || !cart.lines.value.length">{{ busy ? 'Placing order…' : 'Place order' }}</button></form></section><aside class="card order-summary"><h2>Your order</h2><p v-if="!cart.lines.value.length">Your cart is empty. <NuxtLink to="/menu">Browse the menu</NuxtLink>.</p><div v-for="line in cart.lines.value" :key="line.id" class="summary-line"><div><strong>{{ line.name }}</strong><small>Qty {{ line.quantity }}</small></div><button aria-label="Remove item" class="icon-btn" @click="cart.remove(line.id)">×</button></div><div class="summary-total"><span>Subtotal</span><strong>{{ new Intl.NumberFormat(undefined, { style: 'currency', currency: tenant.data.value.data.currency.code }).format(cart.subtotal.value) }}</strong></div></aside></div></div></div></template>
